# Generated by Django 5.1 on 2026-09-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('ip', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, default='', max_length=255)),
                ('os', models.CharField(blank=True, default='', max_length=255)),
                ('biz_system', models.CharField(blank=True, default='', max_length=255)),
                ('level', models.CharField(choices=[('critical', '核心'), ('high', '重要'), ('medium', '一般'), ('low', '低')], default='medium', max_length=16)),
                ('status', models.CharField(choices=[('online', '在线'), ('offline', '下线'), ('unknown', '未知')], default='unknown', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '资产',
                'verbose_name_plural': '资产',
                'db_table': 'asset',
            },
        ),
        migrations.CreateModel(
            name='AssetOwnerMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('ip', models.ForeignKey(db_column='ip', on_delete=django.db.models.deletion.CASCADE, related_name='owner_history', to='assets.asset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '资产负责人映射',
                'verbose_name_plural': '资产负责人映射',
                'db_table': 'asset_owner_map',
            },
        ),
    ]
