# Generated by Django 5.1 on 2026-09-09 08:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assetownermap',
            index=models.Index(fields=['valid_to'], name='asset_owner_valid_t_5de951_idx'),
        ),
    ]
