# Generated by Django 5.1 on 2026-09-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('operator', '运营'), ('leader', '负责人审批'), ('owner', '资产负责人'), ('auditor', '审计只读')], default='owner', max_length=16),
        ),
    ]
