# Generated by Django 5.1 on 2026-09-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_totp_secret_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wecom_userid',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
    ]
