# Generated by Django 5.1 on 2026-09-10 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_dept_d70422_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptLeaderMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dept_leader_maps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '部门负责人映射',
                'verbose_name_plural': '部门负责人映射',
                'db_table': 'dept_leader_map',
                'indexes': [models.Index(fields=['dept_path'], name='dept_leader_dept_pa_23d6bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'dept_path'), name='uniq_user_dept_path')],
            },
        ),
    ]
