# Generated by Django 5.1 on 2026-09-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('imports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SlaPolicy',
            fields=[
                ('severity', models.CharField(choices=[('严重', '严重'), ('高', '高'), ('中', '中'), ('低', '低')], max_length=8, primary_key=True, serialize=False)),
                ('days', models.IntegerField()),
                ('warn_days_before', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'SLA策略',
                'verbose_name_plural': 'SLA策略',
                'db_table': 'sla_policy',
            },
        ),
        migrations.CreateModel(
            name='VulnTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dedup_key', models.CharField(db_index=True, max_length=32, unique=True)),
                ('ip', models.CharField(db_index=True, max_length=45)),
                ('port', models.IntegerField()),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP')], default='tcp', max_length=8)),
                ('service', models.CharField(blank=True, default='', max_length=128)),
                ('plugin_id', models.CharField(blank=True, default='', max_length=64)),
                ('plugin_name', models.CharField(blank=True, default='', max_length=512)),
                ('cve', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(choices=[('严重', '严重'), ('高', '高'), ('中', '中'), ('低', '低')], max_length=8)),
                ('cvss', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('solution', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('待分配', '待分配'), ('待修复', '待修复'), ('待复测', '待复测'), ('已闭合', '已闭合'), ('已延期', '已延期'), ('已忽略', '已忽略')], default='待分配', max_length=16)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('fix_evidence', models.JSONField(blank=True, default=dict)),
                ('delay_until', models.DateTimeField(blank=True, null=True)),
                ('ignore_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='assets.asset')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='imports.scanbatch')),
            ],
            options={
                'verbose_name': '漏洞工单',
                'verbose_name_plural': '漏洞工单',
                'db_table': 'vuln_ticket',
                'indexes': [models.Index(fields=['ip', 'state'], name='vuln_ticket_ip_70d2f2_idx'), models.Index(fields=['assignee', 'state'], name='vuln_ticket_assigne_e362fa_idx'), models.Index(fields=['sla_due_at'], name='vuln_ticket_sla_due_3b4b54_idx')],
            },
        ),
    ]
