# Generated by Django 5.1 on 2026-09-08 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticketattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DelayRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delay_days', models.IntegerField(blank=True, null=True)),
                ('delay_until', models.DateTimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('待审批', '待审批'), ('已批准', '已批准'), ('已驳回', '已驳回')], default='待审批', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decide_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decided_delays', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_requests', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_requests', to='tickets.vulnticket')),
            ],
            options={
                'verbose_name': '延期申请',
                'verbose_name_plural': '延期申请',
                'db_table': 'delay_request',
            },
        ),
    ]
