# Generated by Django 5.1 on 2026-09-09 08:04

from django.conf import settings
from django.db import migrations, models

import apps.tickets.models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_assetownermap_asset_owner_valid_t_5de951_idx'),
        ('imports', '0001_initial'),
        ('tickets', '0005_delayrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketattachment',
            name='file',
            field=models.FileField(upload_to=apps.tickets.models.attachment_upload_to),
        ),
        migrations.AddIndex(
            model_name='vulnticket',
            index=models.Index(fields=['severity'], name='vuln_ticket_severit_877d61_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnticket',
            index=models.Index(fields=['state', 'severity'], name='vuln_ticket_state_d23c40_idx'),
        ),
        migrations.AddIndex(
            model_name='vulnticket',
            index=models.Index(fields=['-updated_at'], name='vuln_ticket_updated_14dfa6_idx'),
        ),
    ]
