# Generated by Django 5.1 on 2026-09-07 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=512)),
                ('file_hash', models.CharField(max_length=64, unique=True)),
                ('source', models.CharField(choices=[('ftp', 'FTP投递'), ('manual', '手工上传')], default='ftp', max_length=16)),
                ('rsas_version', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stats_json', models.JSONField(blank=True, default=dict)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '扫描批次',
                'verbose_name_plural': '扫描批次',
                'db_table': 'scan_batch',
            },
        ),
    ]
